internal enum EXIT_CODES
{
    SUCCESS = 0,
    ERR_NO_PARAMETERS = 1,
    ERR_UNKNOWN_PARAMETER = 2,
    ERR_NOT_ALL_PARAMETERS = 3,
    ERR_PARAMETER_PARSE = 4,
    ERR_NO_CB = 5,
    ERR_LOADING_MODEL = 6,
    ERR_CREATING_MODEL = 7,
    ERR_SAVED_MODEL_NOT_FOUND = 8
}
